# AUTOGENERATED FILE. DO NOT EDIT.
from __future__ import annotations
from exo import *
from exo.libs.externs import select
from exo.stdlib.stdlib import stride
from appleamx_externs import fmax, fmin
from appleamx_pools import APPLE_AMX_POOL_X, APPLE_AMX_POOL_Y, APPLE_AMX_POOL_Z

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f16(dst: [f16][32] @ APPLE_AMX_POOL_Z, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f32(dst: [f32][16] @ APPLE_AMX_POOL_Z, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f64(dst: [f64][8] @ APPLE_AMX_POOL_Z, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_i8(dst: [i8][64] @ APPLE_AMX_POOL_Z, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Z, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Z, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_i32(dst: [i32][16] @ APPLE_AMX_POOL_Z, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_16BIT);")
def apple_amx_extrhx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_16BIT);")
def apple_amx_extrhy_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 2 + {src_data}, AMX_EXTR_16BIT);")
def apple_amx_extrvx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32, 32] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 32
  for j in seq(0, 32):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 2 + {src_data}, AMX_TO_Y | AMX_EXTR_16BIT);")
def apple_amx_extrvy_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32, 32] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 32
  for j in seq(0, 32):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_32BIT);")
def apple_amx_extrhx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_32BIT);")
def apple_amx_extrhy_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 4 + {src_data}, AMX_EXTR_32BIT);")
def apple_amx_extrvx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16, 16] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 16
  for j in seq(0, 16):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 4 + {src_data}, AMX_TO_Y | AMX_EXTR_32BIT);")
def apple_amx_extrvy_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16, 16] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 16
  for j in seq(0, 16):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_64BIT);")
def apple_amx_extrhx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_64BIT);")
def apple_amx_extrhy_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 8 + {src_data}, AMX_EXTR_64BIT);")
def apple_amx_extrvx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8, 8] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 8
  for j in seq(0, 8):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 8 + {src_data}, AMX_TO_Y | AMX_EXTR_64BIT);")
def apple_amx_extrvy_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8, 8] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 8
  for j in seq(0, 8):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_8BIT);")
def apple_amx_extrhx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_8BIT);")
def apple_amx_extrhy_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 1 + {src_data}, AMX_EXTR_8BIT);")
def apple_amx_extrvx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64, 64] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 64
  for j in seq(0, 64):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 1 + {src_data}, AMX_TO_Y | AMX_EXTR_8BIT);")
def apple_amx_extrvy_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64, 64] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 64
  for j in seq(0, 64):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_8BIT);")
def apple_amx_extrhx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_8BIT);")
def apple_amx_extrhy_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 1 + {src_data}, AMX_EXTR_8BIT);")
def apple_amx_extrvx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64, 64] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 64
  for j in seq(0, 64):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 1 + {src_data}, AMX_TO_Y | AMX_EXTR_8BIT);")
def apple_amx_extrvy_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64, 64] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 64
  for j in seq(0, 64):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_16BIT);")
def apple_amx_extrhx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_16BIT);")
def apple_amx_extrhy_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 2 + {src_data}, AMX_EXTR_16BIT);")
def apple_amx_extrvx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32, 32] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 32
  for j in seq(0, 32):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 2 + {src_data}, AMX_TO_Y | AMX_EXTR_16BIT);")
def apple_amx_extrvy_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32, 32] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 32
  for j in seq(0, 32):
    dst[j] = src[j, c]

@instr("AMX_EXTRX_COPY({dst_data}, {src_data});")
def apple_amx_extrx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRY_COPY({dst_data}, {src_data});")
def apple_amx_extry_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_EXTR_32BIT);")
def apple_amx_extrhx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}) * 64, {src_data}, AMX_TO_Y | AMX_EXTR_32BIT);")
def apple_amx_extrhy_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 4 + {src_data}, AMX_EXTR_32BIT);")
def apple_amx_extrvx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16, 16] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 16
  for j in seq(0, 16):
    dst[j] = src[j, c]

@instr("AMX_EXTRV(({dst_data}) * 64, ({c}) * 4 + {src_data}, AMX_TO_Y | AMX_EXTR_32BIT);")
def apple_amx_extrvy_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16, 16] @ APPLE_AMX_POOL_Z, c: index):
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  assert c >= 0
  assert c < 16
  for j in seq(0, 16):
    dst[j] = src[j, c]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fma16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fms16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Z);")
def apple_amx_mul16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA16(0, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = 0.0

@instr("AMX_FMA16(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y);")
def apple_amx_addx16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X);")
def apple_amx_addy16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcy[i]

@instr("AMX_FMA16(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = srcy[i]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fma16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] += srcx[i] * srcy[i]

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fms16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] += -(srcx[i] * srcy[i])

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] = srcx[i] * srcy[i]

@instr("AMX_FMA16(0, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 32):
    dst[i] = 0.0

@instr("AMX_FMA16(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y);")
def apple_amx_addx16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] += srcx[i]

@instr("AMX_FMA16(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X);")
def apple_amx_addy16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] += srcy[i]

@instr("AMX_FMA16(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] = srcx[i]

@instr("AMX_FMA16(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] = srcy[i]

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(5) | AMX_LANE_WIDTH(2));")
def apple_amx_min16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] = fmin(srcx[i], dst[i])

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(7) | AMX_LANE_WIDTH(2));")
def apple_amx_max16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] = fmax(srcx[i], dst[i])

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(4) | AMX_LANE_WIDTH(2));")
def apple_amx_select16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    dst[i] = select(0.0, srcx[i], srcy[i], 0.0)

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(0) | AMX_LANE_WIDTH(2) | AMX_BROADCAST_Y({n}));")
def apple_amx_fma16_vec_lane(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y, n: index):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  assert n >= 0
  assert n < 32
  for i in seq(0, 32):
    dst[i] += srcx[i] * srcy[n]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fma32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fms32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Z);")
def apple_amx_mul32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA32(0, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = 0.0

@instr("AMX_FMA32(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y);")
def apple_amx_addx32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += srcx[j]

@instr("AMX_FMA32(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X);")
def apple_amx_addy32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += srcy[i]

@instr("AMX_FMA32(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = srcx[j]

@instr("AMX_FMA32(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = srcy[i]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fma32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] += srcx[i] * srcy[i]

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fms32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] += -(srcx[i] * srcy[i])

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] = srcx[i] * srcy[i]

@instr("AMX_FMA32(0, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 16):
    dst[i] = 0.0

@instr("AMX_FMA32(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y);")
def apple_amx_addx32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] += srcx[i]

@instr("AMX_FMA32(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X);")
def apple_amx_addy32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] += srcy[i]

@instr("AMX_FMA32(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] = srcx[i]

@instr("AMX_FMA32(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] = srcy[i]

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(5) | AMX_LANE_WIDTH(4));")
def apple_amx_min32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] = fmin(srcx[i], dst[i])

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(7) | AMX_LANE_WIDTH(4));")
def apple_amx_max32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] = fmax(srcx[i], dst[i])

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(4) | AMX_LANE_WIDTH(4));")
def apple_amx_select32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    dst[i] = select(0.0, srcx[i], srcy[i], 0.0)

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(0) | AMX_LANE_WIDTH(4) | AMX_BROADCAST_Y({n}));")
def apple_amx_fma32_vec_lane(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y, n: index):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  assert n >= 0
  assert n < 16
  for i in seq(0, 16):
    dst[i] += srcx[i] * srcy[n]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fma64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, 0);")
def apple_amx_fms64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Z);")
def apple_amx_mul64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA64(0, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = 0.0

@instr("AMX_FMA64(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y);")
def apple_amx_addx64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += srcx[j]

@instr("AMX_FMA64(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X);")
def apple_amx_addy64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += srcy[i]

@instr("AMX_FMA64(0, ({srcx_data}) * 64, {dst_data}, AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = srcx[j]

@instr("AMX_FMA64(({srcy_data}) * 64, 0, {dst_data}, AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = srcy[i]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fma64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] += srcx[i] * srcy[i]

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR);")
def apple_amx_fms64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] += -(srcx[i] * srcy[i])

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] = srcx[i] * srcy[i]

@instr("AMX_FMA64(0, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 8):
    dst[i] = 0.0

@instr("AMX_FMA64(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y);")
def apple_amx_addx64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] += srcx[i]

@instr("AMX_FMA64(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X);")
def apple_amx_addy64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] += srcy[i]

@instr("AMX_FMA64(0, ({srcx_data}) * 64, {dst_data}, AMX_VECTOR | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_movx64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] = srcx[i]

@instr("AMX_FMA64(({srcy_data}) * 64, 0, {dst_data}, AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Z);")
def apple_amx_movy64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] = srcy[i]

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(5) | AMX_LANE_WIDTH(7));")
def apple_amx_min64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] = fmin(srcx[i], dst[i])

@instr("AMX_VECFP(0, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(7) | AMX_LANE_WIDTH(7));")
def apple_amx_max64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] = fmax(srcx[i], dst[i])

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(4) | AMX_LANE_WIDTH(7));")
def apple_amx_select64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    dst[i] = select(0.0, srcx[i], srcy[i], 0.0)

@instr("AMX_VECFP(({srcy_data}) * 64, ({srcx_data}) * 64, {dst_data}, AMX_ALU_MODE(0) | AMX_LANE_WIDTH(7) | AMX_BROADCAST_Y({n}));")
def apple_amx_fma64_vec_lane(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y, n: index):
  assert stride(dst, 0) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  assert n >= 0
  assert n < 8
  for i in seq(0, 8):
    dst[i] += srcx[i] * srcy[n]
