# AUTOGENERATED by gen_appleamx_ops.py. DO NOT EDIT.
from __future__ import annotations
from exo import *
from exo.stdlib.stdlib import stride
from appleamx_pools import APPLE_AMX_POOL_X, APPLE_AMX_POOL_Y, APPLE_AMX_POOL_Z

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_f16(dst: [f16][32] @ APPLE_AMX_POOL_Z, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_f16(dst: [f16][2, 32] @ APPLE_AMX_POOL_X, src: [f16][2, 32] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_f16(dst: [f16][2, 32] @ DRAM, src: [f16][2, 32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_f16(dst: [f16][2, 32] @ APPLE_AMX_POOL_Y, src: [f16][2, 32] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_f16(dst: [f16][2, 32] @ DRAM, src: [f16][2, 32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 2);")
def apple_amx_extrh_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_f32(dst: [f32][16] @ APPLE_AMX_POOL_Z, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_f32(dst: [f32][2, 16] @ APPLE_AMX_POOL_X, src: [f32][2, 16] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_f32(dst: [f32][2, 16] @ DRAM, src: [f32][2, 16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_f32(dst: [f32][2, 16] @ APPLE_AMX_POOL_Y, src: [f32][2, 16] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_f32(dst: [f32][2, 16] @ DRAM, src: [f32][2, 16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 1);")
def apple_amx_extrh_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_f64(dst: [f64][8] @ APPLE_AMX_POOL_Z, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_f64(dst: [f64][2, 8] @ APPLE_AMX_POOL_X, src: [f64][2, 8] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 8
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_f64(dst: [f64][2, 8] @ DRAM, src: [f64][2, 8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 8
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_f64(dst: [f64][2, 8] @ APPLE_AMX_POOL_Y, src: [f64][2, 8] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 8
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_f64(dst: [f64][2, 8] @ DRAM, src: [f64][2, 8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 8
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 0);")
def apple_amx_extrh_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_i8(dst: [i8][64] @ APPLE_AMX_POOL_Z, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_i8(dst: [i8][2, 64] @ APPLE_AMX_POOL_X, src: [i8][2, 64] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_i8(dst: [i8][2, 64] @ DRAM, src: [i8][2, 64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_i8(dst: [i8][2, 64] @ APPLE_AMX_POOL_Y, src: [i8][2, 64] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_i8(dst: [i8][2, 64] @ DRAM, src: [i8][2, 64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 2);")
def apple_amx_extrh_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Z, src: [ui8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_ui8(dst: [ui8][64] @ DRAM, src: [ui8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_ui8(dst: [ui8][2, 64] @ APPLE_AMX_POOL_X, src: [ui8][2, 64] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_ui8(dst: [ui8][2, 64] @ DRAM, src: [ui8][2, 64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_ui8(dst: [ui8][2, 64] @ APPLE_AMX_POOL_Y, src: [ui8][2, 64] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_ui8(dst: [ui8][2, 64] @ DRAM, src: [ui8][2, 64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 64
  for i in seq(0, 2):
    for j in seq(0, 64):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_Y, src: [ui8][64] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 2);")
def apple_amx_extrh_ui8(dst: [ui8][64] @ APPLE_AMX_POOL_X, src: [ui8][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Z, src: [ui16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_ui16(dst: [ui16][32] @ DRAM, src: [ui16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_ui16(dst: [ui16][2, 32] @ APPLE_AMX_POOL_X, src: [ui16][2, 32] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_ui16(dst: [ui16][2, 32] @ DRAM, src: [ui16][2, 32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_ui16(dst: [ui16][2, 32] @ APPLE_AMX_POOL_Y, src: [ui16][2, 32] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_ui16(dst: [ui16][2, 32] @ DRAM, src: [ui16][2, 32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 32
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 2);")
def apple_amx_extrh_ui16(dst: [ui16][32] @ APPLE_AMX_POOL_X, src: [ui16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, ({src_data}), 0);")
def apple_amx_stx_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldy_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, ({src_data}), 0);")
def apple_amx_sty_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}), 0);")
def apple_amx_ldz_i32(dst: [i32][16] @ APPLE_AMX_POOL_Z, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, ({src_data}), 0);")
def apple_amx_stz_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldx2_i32(dst: [i32][2, 16] @ APPLE_AMX_POOL_X, src: [i32][2, 16] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_STX(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_stx2_i32(dst: [i32][2, 16] @ DRAM, src: [i32][2, 16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_LDY(&{src_data}, ({dst_data}), AMX_LDST_PAIR);")
def apple_amx_ldy2_i32(dst: [i32][2, 16] @ APPLE_AMX_POOL_Y, src: [i32][2, 16] @ DRAM):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(src, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_STY(&{dst_data}, ({src_data}), AMX_LDST_PAIR);")
def apple_amx_sty2_i32(dst: [i32][2, 16] @ DRAM, src: [i32][2, 16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(src, 1) == 1
  assert stride(dst, 0) == 16
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, j] = src[i, j]

@instr("AMX_EXTRX_FROM_Y(({dst_data}), ({src_data}));")
def apple_amx_extrx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRY_FROM_X(({dst_data}), ({src_data}));")
def apple_amx_extry_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_EXTRH(({dst_data}), ({src_data}), 1);")
def apple_amx_extrh_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, ({dst_data}) + ({row}) * 2, AMX_LDST_PAIR);")
def apple_amx_ldz2_f16(row: index, dst: [f16][2, 32, 32] @ APPLE_AMX_POOL_Z, src: [f16][64] @ DRAM):
  assert 0 <= row
  assert row < 32
  assert stride(dst, 2) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, row, j] = src[32 * i + j]

@instr("AMX_STZ(&{dst_data}, ({src_data}) + ({row}) * 2, AMX_LDST_PAIR);")
def apple_amx_stz2_f16(row: index, dst: [f16][64] @ DRAM, src: [f16][2, 32, 32] @ APPLE_AMX_POOL_Z):
  assert 0 <= row
  assert row < 32
  assert stride(dst, 0) == 1
  assert stride(src, 2) == 1
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[32 * i + j] = src[i, row, j]

@instr("AMX_EXTRV(({dst_data}), ({src_data}) + ({col}) * 2, 2);")
def apple_amx_extrv_f16(col: index, dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32, 32] @ APPLE_AMX_POOL_Z):
  assert 0 <= col
  assert col < 32
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  for i in seq(0, 32):
    dst[i] = src[i, col]

@instr("AMX_LDZ(&{src_data}, ({dst_data}) + ({row}) * 4, AMX_LDST_PAIR);")
def apple_amx_ldz2_f32(row: index, dst: [f32][2, 16, 16] @ APPLE_AMX_POOL_Z, src: [f32][32] @ DRAM):
  assert 0 <= row
  assert row < 16
  assert stride(dst, 2) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, row, j] = src[16 * i + j]

@instr("AMX_STZ(&{dst_data}, ({src_data}) + ({row}) * 4, AMX_LDST_PAIR);")
def apple_amx_stz2_f32(row: index, dst: [f32][32] @ DRAM, src: [f32][2, 16, 16] @ APPLE_AMX_POOL_Z):
  assert 0 <= row
  assert row < 16
  assert stride(dst, 0) == 1
  assert stride(src, 2) == 1
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[16 * i + j] = src[i, row, j]

@instr("AMX_EXTRV(({dst_data}), ({src_data}) + ({col}) * 4, 1);")
def apple_amx_extrv_f32(col: index, dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16, 16] @ APPLE_AMX_POOL_Z):
  assert 0 <= col
  assert col < 16
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  for i in seq(0, 16):
    dst[i] = src[i, col]

@instr("AMX_LDZ(&{src_data}, ({dst_data}) + ({row}) * 8, AMX_LDST_PAIR);")
def apple_amx_ldz2_f64(row: index, dst: [f64][2, 8, 8] @ APPLE_AMX_POOL_Z, src: [f64][16] @ DRAM):
  assert 0 <= row
  assert row < 8
  assert stride(dst, 2) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[i, row, j] = src[8 * i + j]

@instr("AMX_STZ(&{dst_data}, ({src_data}) + ({row}) * 8, AMX_LDST_PAIR);")
def apple_amx_stz2_f64(row: index, dst: [f64][16] @ DRAM, src: [f64][2, 8, 8] @ APPLE_AMX_POOL_Z):
  assert 0 <= row
  assert row < 8
  assert stride(dst, 0) == 1
  assert stride(src, 2) == 1
  for i in seq(0, 2):
    for j in seq(0, 8):
      dst[8 * i + j] = src[i, row, j]

@instr("AMX_EXTRV(({dst_data}), ({src_data}) + ({col}) * 8, 0);")
def apple_amx_extrv_f64(col: index, dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8, 8] @ APPLE_AMX_POOL_Z):
  assert 0 <= col
  assert col < 8
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  for i in seq(0, 8):
    dst[i] = src[i, col]

@instr("AMX_LDZ(&{src_data}, ({dst_data}) + ({row}) * 2, AMX_LDST_PAIR);")
def apple_amx_ldz2_ui16(row: index, dst: [ui16][2, 32, 32] @ APPLE_AMX_POOL_Z, src: [ui16][64] @ DRAM):
  assert 0 <= row
  assert row < 32
  assert stride(dst, 2) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[i, row, j] = src[32 * i + j]

@instr("AMX_STZ(&{dst_data}, ({src_data}) + ({row}) * 2, AMX_LDST_PAIR);")
def apple_amx_stz2_ui16(row: index, dst: [ui16][64] @ DRAM, src: [ui16][2, 32, 32] @ APPLE_AMX_POOL_Z):
  assert 0 <= row
  assert row < 32
  assert stride(dst, 0) == 1
  assert stride(src, 2) == 1
  for i in seq(0, 2):
    for j in seq(0, 32):
      dst[32 * i + j] = src[i, row, j]

@instr("AMX_EXTRV(({dst_data}), ({src_data}) + ({col}) * 2, 2);")
def apple_amx_extrv_ui16(col: index, dst: [ui16][32] @ APPLE_AMX_POOL_Y, src: [ui16][32, 32] @ APPLE_AMX_POOL_Z):
  assert 0 <= col
  assert col < 32
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  for i in seq(0, 32):
    dst[i] = src[i, col]

@instr("AMX_LDZ(&{src_data}, ({dst_data}) + ({row}) * 4, AMX_LDST_PAIR);")
def apple_amx_ldz2_i32(row: index, dst: [i32][2, 16, 16] @ APPLE_AMX_POOL_Z, src: [i32][32] @ DRAM):
  assert 0 <= row
  assert row < 16
  assert stride(dst, 2) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[i, row, j] = src[16 * i + j]

@instr("AMX_STZ(&{dst_data}, ({src_data}) + ({row}) * 4, AMX_LDST_PAIR);")
def apple_amx_stz2_i32(row: index, dst: [i32][32] @ DRAM, src: [i32][2, 16, 16] @ APPLE_AMX_POOL_Z):
  assert 0 <= row
  assert row < 16
  assert stride(dst, 0) == 1
  assert stride(src, 2) == 1
  for i in seq(0, 2):
    for j in seq(0, 16):
      dst[16 * i + j] = src[i, row, j]

@instr("AMX_EXTRV(({dst_data}), ({src_data}) + ({col}) * 4, 1);")
def apple_amx_extrv_i32(col: index, dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16, 16] @ APPLE_AMX_POOL_Z):
  assert 0 <= col
  assert col < 16
  assert stride(dst, 0) == 1
  assert stride(src, 1) == 1
  for i in seq(0, 16):
    dst[i] = src[i, col]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fma16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fma16_mat_masked(rows: size, cols: size, dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fms16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fms16_mat_masked(rows: size, cols: size, dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z);")
def apple_amx_mul16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_mul16_mat_masked(rows: size, cols: size, dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA16(0, 0, ({dst_data}), AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = 0.0

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fma16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fma16_vec_masked(n: size, dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert n <= 32
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    if i < n:
      dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fms16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fms16_vec_masked(n: size, dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert n <= 32
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    if i < n:
      dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_mul16_vec_masked(n: size, dst: [f16][32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert n <= 32
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    if i < n:
      dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA16(0, 0, ({dst_data}), AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero16_vec(dst: [f16][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 32):
    dst[i] = 0.0

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fma32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fma32_mat_masked(rows: size, cols: size, dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert rows <= 16
  assert 0 < rows
  assert cols <= 16
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      if i < rows:
        if j < cols:
          dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fms32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fms32_mat_masked(rows: size, cols: size, dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert rows <= 16
  assert 0 < rows
  assert cols <= 16
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      if i < rows:
        if j < cols:
          dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z);")
def apple_amx_mul32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_mul32_mat_masked(rows: size, cols: size, dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert rows <= 16
  assert 0 < rows
  assert cols <= 16
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      if i < rows:
        if j < cols:
          dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA32(0, 0, ({dst_data}), AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] = 0.0

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fma32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fma32_vec_masked(n: size, dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert n <= 16
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    if i < n:
      dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fms32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMS32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fms32_vec_masked(n: size, dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert n <= 16
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    if i < n:
      dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA32(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_mul32_vec_masked(n: size, dst: [f32][16] @ APPLE_AMX_POOL_Z, srcy: [f32][16] @ APPLE_AMX_POOL_Y, srcx: [f32][16] @ APPLE_AMX_POOL_X):
  assert n <= 16
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    if i < n:
      dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA32(0, 0, ({dst_data}), AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero32_vec(dst: [f32][16] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 16):
    dst[i] = 0.0

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fma64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fma64_mat_masked(rows: size, cols: size, dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert rows <= 8
  assert 0 < rows
  assert cols <= 8
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      if i < rows:
        if j < cols:
          dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), 0);")
def apple_amx_fms64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fms64_mat_masked(rows: size, cols: size, dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert rows <= 8
  assert 0 < rows
  assert cols <= 8
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      if i < rows:
        if j < cols:
          dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z);")
def apple_amx_mul64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_SKIP_Z | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_mul64_mat_masked(rows: size, cols: size, dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert rows <= 8
  assert 0 < rows
  assert cols <= 8
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      if i < rows:
        if j < cols:
          dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA64(0, 0, ({dst_data}), AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] = 0.0

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fma64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fma64_vec_masked(n: size, dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert n <= 8
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    if i < n:
      dst[i] += srcy[i] * srcx[i]

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR);")
def apple_amx_fms64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMS64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_fms64_vec_masked(n: size, dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert n <= 8
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    if i < n:
      dst[i] += -(srcy[i] * srcx[i])

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z);")
def apple_amx_mul64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA64(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_VECTOR | AMX_SKIP_Z | AMX_ENABLE_X_FIRST({n}));")
def apple_amx_mul64_vec_masked(n: size, dst: [f64][8] @ APPLE_AMX_POOL_Z, srcy: [f64][8] @ APPLE_AMX_POOL_Y, srcx: [f64][8] @ APPLE_AMX_POOL_X):
  assert n <= 8
  assert 0 < n
  assert stride(dst, 0) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 8):
    if i < n:
      dst[i] = srcy[i] * srcx[i]

@instr("AMX_FMA64(0, 0, ({dst_data}), AMX_VECTOR | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero64_vec(dst: [f64][8] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  for i in seq(0, 8):
    dst[i] = 0.0

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32);")
def apple_amx_fma16_mat_f32(dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32 | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fma16_mat_f32_masked(rows: size, cols: size, dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] += srcy[i] * srcx[j]

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32);")
def apple_amx_fms16_mat_f32(dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMS16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32 | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_fms16_mat_f32_masked(rows: size, cols: size, dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] += -(srcy[i] * srcx[j])

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32 | AMX_SKIP_Z);")
def apple_amx_mul16_mat_f32(dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA16(({srcy_data}) * 64, ({srcx_data}) * 64, ({dst_data}), AMX_Z_F32 | AMX_SKIP_Z | AMX_ENABLE_Y_FIRST({rows}) | AMX_ENABLE_X_FIRST({cols}));")
def apple_amx_mul16_mat_f32_masked(rows: size, cols: size, dst: [f32][32, 32] @ APPLE_AMX_POOL_Z, srcy: [f16][32] @ APPLE_AMX_POOL_Y, srcx: [f16][32] @ APPLE_AMX_POOL_X):
  assert rows <= 32
  assert 0 < rows
  assert cols <= 32
  assert 0 < cols
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      if i < rows:
        if j < cols:
          dst[i, j] = srcy[i] * srcx[j]

@instr("AMX_FMA16(0, 0, ({dst_data}), AMX_Z_F32 | AMX_SKIP_X | AMX_SKIP_Y | AMX_SKIP_Z);")
def apple_amx_zero16_mat_f32(dst: [f32][32, 32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] = 0.0

@instr("AMX_LDZI(&{src_data}, ({dst_data}), 0); AMX_LDZI(&{src_data} + 16, ({dst_data}) | 1, 0);")
def apple_amx_ldzi_f32(dst: [f32][32] @ APPLE_AMX_POOL_Z, src: [f32][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZI(&{dst_data}, ({src_data}), 0); AMX_STZI(&{dst_data} + 16, ({src_data}) | 1, 0);")
def apple_amx_stzi_f32(dst: [f32][32] @ DRAM, src: [f32][32] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_MATINT(({srcy_data}) * 64 + ({k}), ({srcx_data}) * 64, ({dst_data}), AMX_MATINT_MAC8_I32 | AMX_MATINT_X_SIGNED | AMX_MATINT_Y_SIGNED);")
def apple_amx_mac8_mat_i32(k: index, dst: [i32][16, 64] @ APPLE_AMX_POOL_Z, srcy: [i8][64] @ APPLE_AMX_POOL_Y, srcx: [i8][64] @ APPLE_AMX_POOL_X):
  assert 0 <= k
  assert k < 4
  assert stride(dst, 1) == 1
  assert stride(srcy, 0) == 1
  assert stride(srcx, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 64):
      dst[i, j] += srcy[4 * i + k] * srcx[j]

@instr("AMX_MATINT(0, 0, ({dst_data}), AMX_MATINT_MAC8_I32 | AMX_MATINT_ZERO_Z);")
def apple_amx_zero8_mat_i32(dst: [i32][16, 64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 1) == 1
  for i in seq(0, 16):
    for j in seq(0, 64):
      dst[i, j] = 0

@instr("amx_ldzq(&{src_data}, ({dst_data}));")
def apple_amx_ldzq_i32(dst: [i32][64] @ APPLE_AMX_POOL_Z, src: [i32][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("amx_stzq(&{dst_data}, ({src_data}));")
def apple_amx_stzq_i32(dst: [i32][64] @ DRAM, src: [i32][64] @ APPLE_AMX_POOL_Z):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]
