# AUTOGENERATED FILE. DO NOT EDIT.
from __future__ import annotations
from exo import *
from exo.stdlib.stdlib import stride
from appleamx_pools import APPLE_AMX_POOL_X, APPLE_AMX_POOL_Y, APPLE_AMX_POOL_Z

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f16(dst: [f16][32] @ APPLE_AMX_POOL_X, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_X):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 32):
        dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f16(dst: [f16][32] @ APPLE_AMX_POOL_Y, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Y):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 32):
        dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f16(dst: [f16][32] @ APPLE_AMX_POOL_Z, src: [f16][32] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 32):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f16(dst: [f16][32] @ DRAM, src: [f16][32] @ APPLE_AMX_POOL_Z):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 32):
        dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f32(dst: [f32][16] @ APPLE_AMX_POOL_X, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_X):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f32(dst: [f32][16] @ APPLE_AMX_POOL_Y, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Y):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f32(dst: [f32][16] @ APPLE_AMX_POOL_Z, src: [f32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f32(dst: [f32][16] @ DRAM, src: [f32][16] @ APPLE_AMX_POOL_Z):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_f64(dst: [f64][8] @ APPLE_AMX_POOL_X, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_X):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 8):
        dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_f64(dst: [f64][8] @ APPLE_AMX_POOL_Y, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Y):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 8):
        dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_f64(dst: [f64][8] @ APPLE_AMX_POOL_Z, src: [f64][8] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 8):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_f64(dst: [f64][8] @ DRAM, src: [f64][8] @ APPLE_AMX_POOL_Z):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 8):
        dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_i8(dst: [i8][64] @ APPLE_AMX_POOL_X, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_X):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 64):
        dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_i8(dst: [i8][64] @ APPLE_AMX_POOL_Y, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Y):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 64):
        dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_i8(dst: [i8][64] @ APPLE_AMX_POOL_Z, src: [i8][64] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 64):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_i8(dst: [i8][64] @ DRAM, src: [i8][64] @ APPLE_AMX_POOL_Z):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 64):
        dst[i] = src[i]

@instr("AMX_LDX(&{src_data}, {dst_data}, 0);")
def apple_amx_ldx_i32(dst: [i32][16] @ APPLE_AMX_POOL_X, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STX(&{dst_data}, {src_data}, 0);")
def apple_amx_stx_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_X):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_LDY(&{src_data}, {dst_data}, 0);")
def apple_amx_ldy_i32(dst: [i32][16] @ APPLE_AMX_POOL_Y, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STY(&{dst_data}, {src_data}, 0);")
def apple_amx_sty_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Y):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_LDZ(&{src_data}, {dst_data}, 0);")
def apple_amx_ldz_i32(dst: [i32][16] @ APPLE_AMX_POOL_Z, src: [i32][16] @ DRAM):
  assert stride(dst, 0) == 1
  assert stride(src, 0) == 1
  for i in seq(0, 16):
    dst[i] = src[i]

@instr("AMX_STZ(&{dst_data}, {src_data}, 0);")
def apple_amx_stz_i32(dst: [i32][16] @ DRAM, src: [i32][16] @ APPLE_AMX_POOL_Z):
    assert stride(dst, 0) == 1
    assert stride(src, 0) == 1
    for i in seq(0, 16):
        dst[i] = src[i]

@instr("AMX_FMA16({srcx_data} * 64, {srcy_data} * 64, {dst_data}, 0);")
def apple_amx_fma16_mat(dst: [f16][32, 32] @ APPLE_AMX_POOL_Z, srcx: [f16][32] @ APPLE_AMX_POOL_X, srcy: [f16][32] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 32):
    for j in seq(0, 32):
      dst[i, j] += srcx[i] * srcy[j]

@instr("AMX_FMA32({srcx_data} * 64, {srcy_data} * 64, {dst_data}, 0);")
def apple_amx_fma32_mat(dst: [f32][16, 16] @ APPLE_AMX_POOL_Z, srcx: [f32][16] @ APPLE_AMX_POOL_X, srcy: [f32][16] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 16):
    for j in seq(0, 16):
      dst[i, j] += srcx[i] * srcy[j]

@instr("AMX_FMA64({srcx_data} * 64, {srcy_data} * 64, {dst_data}, 0);")
def apple_amx_fma64_mat(dst: [f64][8, 8] @ APPLE_AMX_POOL_Z, srcx: [f64][8] @ APPLE_AMX_POOL_X, srcy: [f64][8] @ APPLE_AMX_POOL_Y):
  assert stride(dst, 1) == 1
  assert stride(srcx, 0) == 1
  assert stride(srcy, 0) == 1
  for i in seq(0, 8):
    for j in seq(0, 8):
      dst[i, j] += srcx[i] * srcy[j]